const express = require("express");
const userRouter = require("./userRouter");
const authRouter = require("./authRouter");
const RestaurantRouter = require("./RestaurantRouter");
const RatingRouter = require("./RatingRouter");
const ProductRouter = require("./ProductRouter");
const promoCodeRouter = require("./promoCodeRoutes");
const UtilsRouter = require("./utilsRouter");
const OrderRouter = require("./OrderRouter");
const CartRouter = require("./CartRouter");
const AdminRouter = require("./AdminRouter");
const ServiceRouter = require("./ServiceRouter");
const NoteRouter = require("./NoteRouter");
const PromotionRouter = require("./PromotionRouter");
const BoissonRouter = require("./BoissonRouter");
const PlatRouter = require("./PlatRouter");
const SectionRouter = require("./SectionRouter");
var router = express.Router();
router.get("/", (req, res) => {
  res.status(200).json("Backend server working properly! 🙌 ");
});
router.use("/user/", userRouter);
router.use("/auth/", authRouter);
router.use("/Restaurant/", RestaurantRouter);
router.use("/Rating/", RatingRouter);
router.use("/Product/", ProductRouter);
router.use("/PromoCode/", promoCodeRouter);
router.use("/Utils/", UtilsRouter);
router.use("/Order/", OrderRouter);
router.use("/Admin/", AdminRouter);
router.use("/Plat", PlatRouter);
router.use("/Service/", ServiceRouter);
router.use("/Section/", SectionRouter);
router.use("/Note/", NoteRouter);
router.use("/Boisson/", BoissonRouter);
router.use("/Promotion/", PromotionRouter);
router.use("/ShoppingCart/", CartRouter);
module.exports = router;
